import post from './post'
import author from './author'
import teamMember from './teamMember'
import heroSlide from './heroSlide'
import contactForm from './contactForm'
import customPage from './customPage'
import event from './event'
import sponsor from './sponsor'
import donationPage from './donationPage'
import sponsorshipTier from './sponsorshipTier'
import missionSection from './missionSection'
import programme from './programme'
import announcementModal from './announcementModal'
import eventsSection from './eventsSection'

export const schemaTypes = [post, author, teamMember, heroSlide, contactForm, customPage, event, sponsor, donationPage, sponsorshipTier, missionSection, programme, announcementModal, eventsSection]
