export { default as Home } from './Home'
export { default as Blog } from './Blog'
export { default as BlogPost } from './BlogPost'
export { default as Team } from './Team'
export { default as CustomPage } from './CustomPage'
export { default as Events } from './Events'
export { default as EventDetail } from './EventDetail'
export { default as Sponsors } from './Sponsors'
export { default as Donate } from './Donate'

export { default as About } from './About'
export { PrivacyPolicy, TermsAndConditions } from './Legal'
export { default as Resources } from './Resources'
export { default as ResourceDetail } from './ResourceDetail'
